---
name: Linting
on:
  pull_request:
    branches:
      - master

jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build Dockerfile
        id: docker_build
        uses: docker/build-push-action@v2
